/* ================================================================
   IMPOSTER — word dictionary
   ----------------------------------------------------------------
   Each entry is a pair [CivilianWord, UndercoverWord] of two closely
   linked words. Which one is handed to civilians vs. undercovers is
   randomized every game, so order within a pair doesn't matter — just
   keep the two words tightly related (a "near miss"), so an undercover
   can plausibly blend in but might slip.

   Add or edit freely. Categories show up in the in-game picker, so keep
   each one meaty (~60+ pairs) to stay varied when players lock to it.
   ================================================================ */

export const DICT = {
  "Food & Drink": [
    ["Coffee","Tea"],["Pizza","Lasagna"],["Hamburger","Hot dog"],["Croissant","Baguette"],
    ["Sushi","Sashimi"],["Pancake","Waffle"],["Chocolate","Caramel"],["Ice cream","Frozen yogurt"],
    ["Ketchup","Mayonnaise"],["Butter","Margarine"],["Apple","Pear"],["Banana","Mango"],
    ["Strawberry","Raspberry"],["Lemonade","Iced tea"],["Beer","Cider"],["Wine","Champagne"],
    ["Espresso","Cappuccino"],["Cheese","Yogurt"],["Spaghetti","Noodles"],["Taco","Burrito"],
    ["Donut","Muffin"],["Cookie","Brownie"],["Honey","Jam"],["Soup","Stew"],
    ["Salad","Coleslaw"],["Rice","Couscous"],["Bread","Toast"],["Milkshake","Smoothie"],
    ["Popcorn","Nachos"],["French fries","Potato chips"],["Orange","Tangerine"],["Grape","Cherry"],
    ["Watermelon","Cantaloupe"],["Peach","Apricot"],["Pineapple","Kiwi"],["Blueberry","Blackberry"],
    ["Lime","Lemon"],["Coconut","Almond"],["Walnut","Hazelnut"],["Peanut","Cashew"],
    ["Carrot","Parsnip"],["Potato","Sweet potato"],["Tomato","Bell pepper"],["Cucumber","Zucchini"],
    ["Onion","Garlic"],["Broccoli","Cauliflower"],["Spinach","Lettuce"],["Corn","Peas"],
    ["Eggplant","Pumpkin"],["Steak","Roast"],["Bacon","Ham"],["Sausage","Salami"],
    ["Chicken","Turkey"],["Meatball","Nugget"],["Omelette","Scrambled eggs"],["Cereal","Granola"],
    ["Porridge","Oatmeal"],["Bagel","Pretzel"],["Sandwich","Wrap"],["Pie","Tart"],
    ["Cake","Cupcake"],["Pudding","Custard"],["Jelly","Marmalade"],["Syrup","Molasses"],
    ["Vinegar","Mustard"],["Salt","Pepper"],["Sugar","Sweetener"],["Soda","Sparkling water"],
    ["Cocktail","Mocktail"],["Whiskey","Rum"],["Vodka","Gin"],["Hot chocolate","Mulled wine"],
    ["Curry","Chili"],["Dumpling","Ravioli"],
  ],
  "Animals": [
    ["Dog","Wolf"],["Cat","Lynx"],["Horse","Donkey"],["Cow","Buffalo"],
    ["Sheep","Goat"],["Rabbit","Hare"],["Mouse","Rat"],["Lion","Tiger"],
    ["Leopard","Cheetah"],["Crocodile","Alligator"],["Turtle","Tortoise"],["Frog","Toad"],
    ["Eagle","Hawk"],["Owl","Bat"],["Penguin","Ostrich"],["Dolphin","Whale"],
    ["Shark","Orca"],["Octopus","Squid"],["Crab","Lobster"],["Bee","Wasp"],
    ["Butterfly","Moth"],["Ant","Termite"],["Spider","Scorpion"],["Snake","Eel"],
    ["Kangaroo","Wallaby"],["Gorilla","Chimpanzee"],["Elephant","Mammoth"],["Hippo","Rhino"],
    ["Camel","Llama"],["Fox","Coyote"],["Deer","Elk"],["Moose","Reindeer"],
    ["Bear","Panda"],["Raccoon","Badger"],["Squirrel","Chipmunk"],["Hedgehog","Porcupine"],
    ["Otter","Beaver"],["Seal","Walrus"],["Jellyfish","Starfish"],["Seahorse","Pufferfish"],
    ["Salmon","Trout"],["Tuna","Cod"],["Goldfish","Guppy"],["Parrot","Cockatoo"],
    ["Peacock","Pheasant"],["Swan","Goose"],["Duck","Pelican"],["Flamingo","Stork"],
    ["Crow","Raven"],["Sparrow","Robin"],["Pigeon","Dove"],["Woodpecker","Kingfisher"],
    ["Hummingbird","Dragonfly"],["Ladybug","Beetle"],["Grasshopper","Cricket"],["Snail","Slug"],
    ["Worm","Caterpillar"],["Chameleon","Iguana"],["Gecko","Salamander"],["Cobra","Python"],
    ["Rattlesnake","Viper"],["Panther","Jaguar"],["Cougar","Puma"],["Hyena","Jackal"],
    ["Zebra","Giraffe"],["Antelope","Gazelle"],["Bison","Yak"],["Boar","Pig"],
    ["Ferret","Weasel"],["Mole","Gopher"],["Monkey","Baboon"],["Sloth","Koala"],
    ["Platypus","Armadillo"],["Meerkat","Mongoose"],
  ],
  "Places": [
    ["Beach","Desert"],["Mountain","Volcano"],["Forest","Jungle"],["River","Canal"],
    ["Lake","Pond"],["Hotel","Hostel"],["Hospital","Pharmacy"],["School","University"],
    ["Library","Bookstore"],["Museum","Art gallery"],["Cinema","Theater"],["Airport","Train station"],
    ["Supermarket","Farmers market"],["Restaurant","Food truck"],["Church","Temple"],["Castle","Palace"],
    ["Prison","Courthouse"],["Gym","Yoga studio"],["Park","Playground"],["Zoo","Aquarium"],
    ["Farm","Ranch"],["Island","Peninsula"],["Cave","Tunnel"],["Bridge","Dam"],
    ["Lighthouse","Windmill"],["Bakery","Butcher shop"],["Cafe","Diner"],["Bar","Nightclub"],
    ["Bank","Post office"],["Stadium","Arena"],["Skatepark","Bowling alley"],["Casino","Arcade"],
    ["Spa","Sauna"],["Barbershop","Nail salon"],["Garage","Workshop"],["Warehouse","Factory"],
    ["Office","Cubicle"],["Classroom","Lecture hall"],["Kitchen","Pantry"],["Bathroom","Laundry room"],
    ["Bedroom","Attic"],["Basement","Cellar"],["Balcony","Terrace"],["Garden","Greenhouse"],
    ["Cemetery","Crypt"],["Mosque","Cathedral"],["Harbor","Marina"],["Pier","Boardwalk"],
    ["Waterfall","Geyser"],["Plateau","Ridge"],["Meadow","Prairie"],["Swamp","Marsh"],
    ["Canyon","Cliff"],["Valley","Gorge"],["Reef","Lagoon"],["Oasis","Waterhole"],
    ["Village","Town"],["City","Suburb"],["Street","Alley"],["Highway","Roundabout"],
    ["Subway","Bus stop"],["Parking lot","Driveway"],["Mall","Boutique"],["Deli","Grocery store"],
    ["Observatory","Planetarium"],["Aquarium","Terrarium"],["Vineyard","Orchard"],["Quarry","Mine"],
    ["Fountain","Well"],["Ruins","Monument"],["Embassy","Consulate"],["Studio","Gallery"],
  ],
  "Jobs & Roles": [
    ["Doctor","Nurse"],["Teacher","Professor"],["Chef","Baker"],["Pilot","Flight attendant"],
    ["Police officer","Security guard"],["Firefighter","Paramedic"],["Lawyer","Judge"],["Actor","Stuntman"],
    ["Singer","Rapper"],["Painter","Sculptor"],["Plumber","Electrician"],["Carpenter","Blacksmith"],
    ["Farmer","Fisherman"],["Dentist","Optician"],["Barber","Hairdresser"],["Journalist","Photographer"],
    ["Astronaut","Scientist"],["Soldier","Sailor"],["Waiter","Bartender"],["Architect","Engineer"],
    ["Programmer","Graphic designer"],["Mailman","Delivery driver"],["Veterinarian","Zookeeper"],["Magician","Clown"],
    ["Detective","Spy"],["Cashier","Accountant"],["Banker","Broker"],["Surgeon","Therapist"],
    ["Librarian","Curator"],["Coach","Referee"],["Athlete","Trainer"],["Dancer","Choreographer"],
    ["Musician","Conductor"],["Writer","Editor"],["Poet","Novelist"],["Comedian","Host"],
    ["Director","Producer"],["Model","Stylist"],["Tailor","Cobbler"],["Jeweler","Watchmaker"],
    ["Florist","Gardener"],["Chemist","Biologist"],["Mechanic","Technician"],["Welder","Mason"],
    ["Miner","Driller"],["Lumberjack","Ranger"],["Shepherd","Cowboy"],["Hunter","Trapper"],
    ["Butcher","Fishmonger"],["Brewer","Winemaker"],["Pharmacist","Herbalist"],["Midwife","Pediatrician"],
    ["Locksmith","Handyman"],["Janitor","Housekeeper"],["Cook","Sous chef"],["Butler","Maid"],
    ["Diplomat","Ambassador"],["Politician","Mayor"],["King","Emperor"],["Queen","Princess"],
    ["Knight","Guard"],["Priest","Monk"],["Prophet","Oracle"],["Captain","Admiral"],
    ["General","Sergeant"],["Wizard","Alchemist"],["Pirate","Smuggler"],["Referee","Umpire"],
    ["Surveyor","Cartographer"],["Auctioneer","Salesman"],
  ],
  "Sports & Games": [
    ["Football","Rugby"],["Basketball","Volleyball"],["Tennis","Badminton"],["Table tennis","Padel"],
    ["Golf","Mini golf"],["Boxing","Wrestling"],["Karate","Judo"],["Swimming","Diving"],
    ["Surfing","Windsurfing"],["Skiing","Snowboarding"],["Ice skating","Rollerblading"],["Marathon","Sprint"],
    ["Chess","Checkers"],["Poker","Blackjack"],["Darts","Archery"],["Bowling","Petanque"],
    ["Monopoly","Risk"],["Hide and seek","Tag"],["Jenga","Dominoes"],["Sudoku","Crossword"],
    ["Skateboarding","BMX"],["Fishing","Hunting"],["Rock climbing","Bouldering"],["Gymnastics","Acrobatics"],
    ["Cycling","Spinning"],["Baseball","Cricket"],["Hockey","Lacrosse"],["Handball","Water polo"],
    ["Fencing","Kendo"],["Taekwondo","Kickboxing"],["Rowing","Kayaking"],["Sailing","Canoeing"],
    ["Curling","Bobsled"],["Luge","Skeleton"],["Ski jumping","Slalom"],["Triathlon","Decathlon"],
    ["Hurdles","Long jump"],["High jump","Pole vault"],["Shot put","Discus"],["Javelin","Hammer throw"],
    ["Weightlifting","Powerlifting"],["Cheerleading","Figure skating"],["Polo","Equestrian"],["Rodeo","Bull riding"],
    ["Paragliding","Skydiving"],["Bungee jumping","Zip lining"],["Parkour","Free running"],["Snorkeling","Scuba diving"],
    ["Billiards","Snooker"],["Foosball","Air hockey"],["Pinball","Whack-a-mole"],["Marbles","Jacks"],
    ["Hopscotch","Jump rope"],["Dodgeball","Kickball"],["Frisbee","Boomerang"],["Charades","Pictionary"],
    ["Scrabble","Bananagrams"],["Solitaire","Uno"],["Bingo","Roulette"],["Backgammon","Mancala"],
    ["Go","Shogi"],["Twister","Limbo"],["Musical chairs","Freeze dance"],["Tug of war","Arm wrestling"],
    ["Paintball","Laser tag"],["Go-karting","Bumper cars"],["Mahjong","Rummy"],["Cluedo","Trivia"],
    ["Yo-yo","Hula hoop"],["Rubik's cube","Jigsaw puzzle"],
  ],
  "Fantasy & Fiction": [
    ["Superhero","Villain"],["Vampire","Zombie"],["Ghost","Skeleton"],["Witch","Wizard"],
    ["Dragon","Dinosaur"],["Unicorn","Pegasus"],["Mermaid","Siren"],["Pirate","Viking"],
    ["Knight","Samurai"],["Robot","Cyborg"],["Alien","Monster"],["Fairy","Elf"],
    ["Giant","Ogre"],["Santa Claus","Tooth fairy"],["Werewolf","Bigfoot"],["Genie","Leprechaun"],
    ["Mummy","Frankenstein"],["Angel","Cupid"],["Time machine","Teleporter"],["Treasure map","Crystal ball"],
    ["Goblin","Troll"],["Dwarf","Gnome"],["Phoenix","Griffin"],["Centaur","Minotaur"],
    ["Kraken","Leviathan"],["Cyclops","Hydra"],["Sphinx","Chimera"],["Basilisk","Gorgon"],
    ["Sorcerer","Necromancer"],["Paladin","Barbarian"],["Ranger","Rogue"],["Bard","Jester"],
    ["Warlock","Druid"],["Demon","Imp"],["Banshee","Poltergeist"],["Wraith","Specter"],
    ["Golem","Gargoyle"],["Yeti","Kappa"],["Fairy godmother","Wicked stepmother"],["Prince Charming","Frog prince"],
    ["Dark lord","Chosen one"],["Wand","Staff"],["Spellbook","Scroll"],["Potion","Elixir"],
    ["Amulet","Talisman"],["Enchanted forest","Haunted house"],["Dungeon","Lair"],["Portal","Wormhole"],
    ["Invisibility cloak","Magic carpet"],["Excalibur","Holy grail"],["Fountain of youth","Philosopher's stone"],["Curse","Blessing"],
    ["Prophecy","Riddle"],["Quest","Crusade"],["Kingdom","Empire"],["Throne","Crown"],
    ["Sword","Shield"],["Bow","Crossbow"],["Catapult","Trebuchet"],["Chariot","Galleon"],
    ["Undead","Ghoul"],["Shapeshifter","Doppelganger"],["Fortune teller","Soothsayer"],["Warrior","Gladiator"],
    ["Space marine","Star pilot"],["Mad scientist","Evil genius"],["Sidekick","Henchman"],["Nemesis","Rival"],
    ["Force field","Death ray"],["Flying saucer","Mothership"],
  ],
  "Objects & Home": [
    ["Chair","Stool"],["Sofa","Armchair"],["Table","Desk"],["Bed","Hammock"],
    ["Pillow","Cushion"],["Blanket","Duvet"],["Lamp","Candle"],["Mirror","Window"],
    ["Clock","Watch"],["Umbrella","Raincoat"],["Backpack","Suitcase"],["Wallet","Handbag"],
    ["Glasses","Sunglasses"],["Hat","Cap"],["Scarf","Tie"],["Gloves","Mittens"],
    ["Sneakers","Boots"],["Toothbrush","Toothpaste"],["Soap","Shampoo"],["Towel","Bathrobe"],
    ["Fork","Spoon"],["Knife","Scissors"],["Mug","Glass"],["Plate","Bowl"],
    ["Kettle","Teapot"],["Fridge","Freezer"],["Oven","Microwave"],["Washing machine","Dishwasher"],
    ["Vacuum cleaner","Broom"],["Ladder","Stairs"],["Bucket","Basin"],["Mop","Sponge"],
    ["Dustpan","Brush"],["Hammer","Mallet"],["Screwdriver","Wrench"],["Nail","Screw"],
    ["Drill","Saw"],["Pliers","Tongs"],["Tape","Glue"],["Rope","Chain"],
    ["Key","Padlock"],["Doorbell","Knocker"],["Curtain","Blind"],["Rug","Carpet"],
    ["Vase","Pot"],["Frame","Poster"],["Shelf","Cabinet"],["Drawer","Wardrobe"],
    ["Basket","Crate"],["Jar","Tin"],["Bottle","Flask"],["Napkin","Tissue"],
    ["Plate rack","Cutting board"],["Whisk","Spatula"],["Ladle","Grater"],["Colander","Sieve"],
    ["Blender","Mixer"],["Toaster","Grill"],["Iron","Hairdryer"],["Fan","Heater"],
    ["Thermostat","Doorknob"],["Light switch","Power outlet"],["Extension cord","Adapter"],["Flashlight","Lantern"],
    ["Matchbox","Lighter"],["Alarm clock","Hourglass"],["Notebook","Diary"],["Pen","Pencil"],
    ["Eraser","Sharpener"],["Stapler","Hole punch"],["Ruler","Compass"],["Envelope","Stamp"],
  ],
  "Technology": [
    ["Smartphone","Tablet"],["Laptop","Desktop computer"],["Keyboard","Computer mouse"],["Headphones","Earbuds"],
    ["Television","Projector"],["Camera","Webcam"],["Drone","Satellite"],["USB stick","Hard drive"],
    ["Wi-Fi","Bluetooth"],["Email","Text message"],["Calculator","Abacus"],["Battery","Power bank"],
    ["Smartwatch","Fitness tracker"],["GPS","Compass"],["Password","Fingerprint"],["Router","Modem"],
    ["Monitor","Screen"],["Printer","Scanner"],["Speaker","Microphone"],["Charger","Cable"],
    ["Console","Controller"],["Joystick","Gamepad"],["Processor","Graphics card"],["Memory","Storage"],
    ["Motherboard","Circuit board"],["Server","Database"],["Website","App"],["Browser","Search engine"],
    ["Firewall","Antivirus"],["Cloud","Backup"],["Robot","Drone"],["Sensor","Detector"],
    ["Barcode","QR code"],["Touchscreen","Trackpad"],["Stylus","Pointer"],["Emoji","Sticker"],
    ["Podcast","Audiobook"],["Streaming","Download"],["Hashtag","Username"],["Notification","Reminder"],
    ["Selfie","Screenshot"],["Filter","Sticker pack"],["Livestream","Broadcast"],["Avatar","Profile picture"],
    ["Cryptocurrency","Stock"],["Blockchain","Ledger"],["Algorithm","Formula"],["Code","Script"],
    ["Bug","Glitch"],["Update","Upgrade"],["Software","Firmware"],["Widget","Gadget"],
    ["Cursor","Icon"],["Folder","File"],["Playlist","Album"],["Ringtone","Alarm tone"],
    ["Voice assistant","Chatbot"],["Solar panel","Wind turbine"],["Electric car","Hoverboard"],["3D printer","Laser cutter"],
    ["Virtual reality","Augmented reality"],["Hologram","Projection"],["Nanochip","Microchip"],["Antenna","Dish"],
    ["Remote control","Keypad"],["Turntable","Cassette player"],["Walkie-talkie","Intercom"],["Metal detector","Radar"],
    ["Thermometer","Barometer"],["Telescope","Microscope"],
  ],
  "Nature & Weather": [
    ["Sun","Moon"],["Star","Planet"],["Rain","Drizzle"],["Snow","Hail"],
    ["Thunder","Lightning"],["Rainbow","Northern lights"],["Cloud","Fog"],["Tornado","Hurricane"],
    ["Earthquake","Avalanche"],["Rose","Tulip"],["Tree","Bush"],["Grass","Moss"],
    ["Leaf","Petal"],["Cactus","Palm tree"],["Mushroom","Truffle"],["Wave","Tide"],
    ["Sand","Mud"],["Ice","Frost"],["Sunrise","Sunset"],["Meteor","Comet"],
    ["Wind","Breeze"],["Storm","Blizzard"],["Flood","Drought"],["Dew","Mist"],
    ["Puddle","Stream"],["Waterfall","Rapids"],["Boulder","Pebble"],["Cliff","Dune"],
    ["Oak","Pine"],["Maple","Birch"],["Willow","Cypress"],["Bamboo","Fern"],
    ["Ivy","Vine"],["Sunflower","Daisy"],["Lily","Orchid"],["Daffodil","Poppy"],
    ["Lavender","Jasmine"],["Clover","Dandelion"],["Acorn","Pinecone"],["Berry","Nut"],
    ["Seed","Sprout"],["Root","Stem"],["Bark","Trunk"],["Branch","Twig"],
    ["Coral","Seaweed"],["Shell","Pearl"],["Crystal","Gemstone"],["Diamond","Ruby"],
    ["Emerald","Sapphire"],["Gold","Silver"],["Copper","Bronze"],["Lava","Magma"],
    ["Ash","Soot"],["Smoke","Steam"],["Icicle","Snowflake"],["Glacier","Iceberg"],
    ["Tsunami","Whirlpool"],["Cyclone","Typhoon"],["Heatwave","Cold snap"],["Monsoon","Downpour"],
    ["Sleet","Slush"],["Humidity","Pressure"],["Aurora","Eclipse"],["Constellation","Galaxy"],
    ["Nebula","Supernova"],["Crater","Canyon"],["Fossil","Amber"],["Geyser","Hot spring"],
    ["Reef","Atoll"],["Tundra","Savanna"],
  ],
  "Transport & Travel": [
    ["Car","Taxi"],["Bus","Tram"],["Train","Metro"],["Bicycle","Scooter"],
    ["Motorcycle","Moped"],["Truck","Van"],["Airplane","Helicopter"],["Hot air balloon","Zeppelin"],
    ["Rowboat","Canoe"],["Cruise ship","Yacht"],["Rocket","Spaceship"],["Ambulance","Fire truck"],
    ["Tractor","Bulldozer"],["Traffic light","Stop sign"],["Passport","Boarding pass"],["Ferry","Barge"],
    ["Submarine","Torpedo"],["Jet ski","Speedboat"],["Sailboat","Catamaran"],["Gondola","Kayak"],
    ["Segway","Skateboard"],["Rickshaw","Carriage"],["Sled","Toboggan"],["Cable car","Chairlift"],
    ["Monorail","Trolley"],["Freight train","Steam locomotive"],["Pickup truck","Jeep"],["Limousine","Convertible"],
    ["Race car","Go-kart"],["Forklift","Crane"],["Excavator","Dump truck"],["Tank","Humvee"],
    ["Fighter jet","Bomber"],["Glider","Biplane"],["Seaplane","Airship"],["Tricycle","Unicycle"],
    ["Wheelbarrow","Trolley cart"],["Stroller","Wheelchair"],["Elevator","Escalator"],["Zipline","Ski lift"],
    ["Landmark","Signpost"],["Duffel bag","Garment bag"],["Ticket","Reservation"],["Runway","Taxiway"],
    ["Harbor","Dock"],["Anchor","Rudder"],["Sail","Paddle"],["Tire","Wheel"],
    ["Engine","Motor"],["Steering wheel","Handlebar"],["Seatbelt","Airbag"],["Headlight","Taillight"],
    ["Horn","Siren"],["Fuel","Charger"],["Roadmap","Itinerary"],["Highway","Freeway"],
    ["Toll booth","Checkpoint"],["Gas station","Rest stop"],["Parking meter","Speed bump"],["Crosswalk","Zebra crossing"],
    ["Luggage cart","Trolley bag"],["Life jacket","Parachute"],["Snowmobile","Dune buggy"],["Camper van","Trailer"],
    ["Hovercraft","Airboat"],["Tugboat","Trawler"],["Cargo ship","Tanker"],["Lifeboat","Dinghy"],
    ["Snowplow","Street sweeper"],["Tow truck","Cement mixer"],["Cable ferry","Water taxi"],["Pedal boat","Rowing shell"],
  ],
  "Everyday Life": [
    ["Birthday","Wedding"],["Christmas","New Year's Eve"],["Halloween","April Fools"],["Summer","Spring"],
    ["Winter","Autumn"],["Breakfast","Brunch"],["Homework","Exam"],["Newspaper","Magazine"],
    ["Comic book","Novel"],["Cash","Credit card"],["Piggy bank","Safe"],["Lottery","Casino"],
    ["Gift","Souvenir"],["Fireworks","Sparkler"],["Dream","Nightmare"],["Meeting","Interview"],
    ["Vacation","Weekend"],["Alarm","Snooze"],["Commute","Traffic jam"],["Shopping list","Recipe"],
    ["Laundry","Dishes"],["Grocery run","Errand"],["Nap","Bedtime"],["Sunbath","Picnic"],
    ["Campfire","Barbecue"],["Sleepover","Camping trip"],["Road trip","City break"],["Concert","Festival"],
    ["Parade","Carnival"],["Graduation","Retirement"],["Anniversary","Reunion"],["Baby shower","Housewarming"],
    ["Funeral","Memorial"],["Date night","First date"],["Breakup","Makeup"],["Handshake","High five"],
    ["Hug","Kiss"],["Selfie","Group photo"],["Password","PIN"],["Receipt","Invoice"],
    ["Coupon","Discount"],["Tip","Bribe"],["Allowance","Salary"],["Rent","Mortgage"],
    ["Bill","Fine"],["Queue","Waiting room"],["Rush hour","Lunch break"],["Overtime","Deadline"],
    ["Chore","Task"],["Habit","Routine"],["Resolution","Goal"],["Secret","Rumor"],
    ["Argument","Debate"],["Apology","Excuse"],["Compliment","Insult"],["Promise","Threat"],
    ["Whisper","Shout"],["Gossip","Lecture"],["Joke","Prank"],["Riddle","Puzzle"],
    ["Superstition","Tradition"],["Wish","Regret"],["Memory","Souvenir"],["Celebration","Ceremony"],
    ["Toast","Speech"],["Countdown","Timer"],["To-do list","Calendar"],["Bucket list","Wish list"],
    ["Spring cleaning","Yard sale"],["Grocery cart","Shopping bag"],["Name tag","Lanyard"],["Guest list","Seating chart"],
  ],
  "Body & Health": [
    ["Heart","Lung"],["Brain","Skull"],["Stomach","Liver"],["Kidney","Bladder"],
    ["Muscle","Bone"],["Skin","Hair"],["Eye","Ear"],["Nose","Mouth"],
    ["Tooth","Tongue"],["Lip","Cheek"],["Chin","Jaw"],["Forehead","Eyebrow"],
    ["Neck","Shoulder"],["Arm","Leg"],["Elbow","Knee"],["Wrist","Ankle"],
    ["Hand","Foot"],["Finger","Toe"],["Thumb","Nail"],["Palm","Sole"],
    ["Rib","Spine"],["Hip","Pelvis"],["Vein","Artery"],["Blood","Bone marrow"],
    ["Nerve","Tendon"],["Cough","Sneeze"],["Fever","Chill"],["Headache","Migraine"],
    ["Bruise","Scar"],["Cut","Scrape"],["Blister","Rash"],["Splinter","Sting"],
    ["Cold","Flu"],["Allergy","Asthma"],["Cramp","Sprain"],["Fracture","Dislocation"],
    ["Bandage","Cast"],["Plaster","Stitches"],["Crutch","Wheelchair"],["Pill","Syrup"],
    ["Vitamin","Supplement"],["Vaccine","Antibiotic"],["Thermometer","Stethoscope"],["Syringe","Scalpel"],
    ["X-ray","Ultrasound"],["Checkup","Surgery"],["Diet","Fast"],["Workout","Stretch"],
    ["Yoga","Pilates"],["Jogging","Walking"],["Sit-up","Push-up"],["Squat","Lunge"],
    ["Protein","Carbohydrate"],["Calorie","Nutrient"],["Sleep","Rest"],["Snore","Yawn"],
    ["Hiccup","Burp"],["Blink","Wink"],["Smile","Frown"],["Laugh","Cry"],
    ["Sweat","Tears"],["Pulse","Heartbeat"],["Breath","Sigh"],["Appetite","Thirst"],
    ["Posture","Balance"],["Reflex","Instinct"],["Immune system","Metabolism"],["Bandaid","Ointment"],
    ["Wrinkle","Freckle"],["Dimple","Mole"],["Eyelash","Eyelid"],["Knuckle","Joint"],
  ],
  "Music, Art & Media": [
    ["Guitar","Ukulele"],["Piano","Keyboard"],["Violin","Cello"],["Drums","Bongos"],
    ["Flute","Clarinet"],["Trumpet","Trombone"],["Saxophone","Harmonica"],["Harp","Lyre"],
    ["Accordion","Bagpipes"],["Xylophone","Marimba"],["Tambourine","Maracas"],["Banjo","Mandolin"],
    ["Microphone","Megaphone"],["Speaker","Amplifier"],["Record","Cassette"],["Vinyl","CD"],
    ["Melody","Rhythm"],["Chord","Note"],["Verse","Chorus"],["Lyrics","Poem"],
    ["Choir","Band"],["Orchestra","Ensemble"],["Solo","Duet"],["Concert","Recital"],
    ["Opera","Musical"],["Ballet","Tap dance"],["Jazz","Blues"],["Rock","Metal"],
    ["Pop","Hip-hop"],["Classical","Folk"],["Reggae","Ska"],["Techno","House"],
    ["Painting","Sketch"],["Portrait","Landscape"],["Mural","Graffiti"],["Sculpture","Statue"],
    ["Canvas","Easel"],["Paintbrush","Palette"],["Watercolor","Oil paint"],["Crayon","Marker"],
    ["Charcoal","Pastel"],["Pottery","Origami"],["Mosaic","Collage"],["Tattoo","Henna"],
    ["Photograph","Painting"],["Gallery","Exhibition"],["Museum","Auction"],["Frame","Pedestal"],
    ["Movie","Documentary"],["Cartoon","Anime"],["Sitcom","Drama"],["Thriller","Horror"],
    ["Comedy","Romance"],["Trailer","Teaser"],["Sequel","Prequel"],["Director","Screenwriter"],
    ["Actor","Extra"],["Script","Screenplay"],["Scene","Take"],["Subtitle","Caption"],
    ["Novel","Poem"],["Chapter","Paragraph"],["Author","Illustrator"],["Comic","Graphic novel"],
    ["Stage","Backstage"],["Curtain call","Encore"],["Spotlight","Floodlight"],["Award","Trophy"],
    ["Sheet music","Songbook"],["Metronome","Tuning fork"],["Jukebox","Music box"],["Album cover","Movie poster"],
  ],
  "Clothing & Style": [
    ["Shirt","Blouse"],["T-shirt","Tank top"],["Sweater","Cardigan"],["Hoodie","Sweatshirt"],
    ["Jacket","Blazer"],["Coat","Trench coat"],["Vest","Waistcoat"],["Jeans","Trousers"],
    ["Shorts","Skirt"],["Dress","Gown"],["Suit","Tuxedo"],["Pajamas","Nightgown"],
    ["Socks","Stockings"],["Tights","Leggings"],["Underwear","Swimsuit"],["Bikini","Trunks"],
    ["Sneakers","Trainers"],["Sandals","Flip-flops"],["Heels","Flats"],["Boots","Loafers"],
    ["Slippers","Clogs"],["Hat","Beanie"],["Cap","Beret"],["Helmet","Hood"],
    ["Scarf","Shawl"],["Handkerchief","Bandana"],["Belt","Suspenders"],["Tie","Bow tie"],
    ["Necklace","Choker"],["Bracelet","Bangle"],["Ring","Earring"],["Brooch","Pin"],
    ["Watch","Cufflink"],["Sunglasses","Goggles"],["Handbag","Clutch"],["Backpack","Tote"],
    ["Wallet","Purse"],["Umbrella","Parasol"],["Apron","Overalls"],["Uniform","Costume"],
    ["Robe","Kimono"],["Poncho","Cape"],["Sari","Kilt"],["Turban","Headscarf"],
    ["Veil","Bonnet"],["Corset","Girdle"],["Cufflinks","Tie clip"],["Button","Zipper"],
    ["Collar","Cuff"],["Sleeve","Hem"],["Pocket","Pouch"],["Lace","Ribbon"],
    ["Denim","Corduroy"],["Silk","Satin"],["Wool","Cashmere"],["Cotton","Linen"],
    ["Leather","Suede"],["Velvet","Fleece"],["Polyester","Nylon"],["Fur","Feather"],
    ["Stripes","Polka dots"],["Plaid","Checkered"],["Camouflage","Tie-dye"],["Sequins","Glitter"],
    ["Makeup","Lipstick"],["Mascara","Eyeliner"],["Perfume","Cologne"],["Nail polish","Foundation"],
    ["Blush","Concealer"],["Eyeshadow","Highlighter"],
  ],
  "World & Landmarks": [
    ["France","Italy"],["Spain","Portugal"],["Germany","Austria"],["Norway","Sweden"],
    ["Denmark","Finland"],["Netherlands","Belgium"],["Switzerland","Liechtenstein"],["Greece","Turkey"],
    ["Poland","Hungary"],["Ireland","Scotland"],["China","Japan"],["South Korea","North Korea"],
    ["India","Pakistan"],["Thailand","Vietnam"],["Indonesia","Philippines"],["Iran","Iraq"],
    ["Saudi Arabia","United Arab Emirates"],["Egypt","Morocco"],["Kenya","Tanzania"],["Nigeria","Ghana"],
    ["South Africa","Zimbabwe"],["Brazil","Argentina"],["Peru","Chile"],["Mexico","Colombia"],
    ["Cuba","Jamaica"],["Canada","United States"],["Australia","New Zealand"],["Iceland","Greenland"],
    ["Europe","Asia"],["Africa","South America"],["North America","Australia"],["Antarctica","Arctic"],
    ["Middle East","Caribbean"],["Paris","London"],["Rome","Athens"],["Berlin","Vienna"],
    ["Barcelona","Madrid"],["Amsterdam","Brussels"],["Venice","Florence"],["New York","Chicago"],
    ["Los Angeles","Las Vegas"],["Tokyo","Osaka"],["Seoul","Beijing"],["Bangkok","Singapore"],
    ["Dubai","Doha"],["Istanbul","Cairo"],["Moscow","Saint Petersburg"],["Sydney","Melbourne"],
    ["Rio de Janeiro","São Paulo"],["Mumbai","Delhi"],["Eiffel Tower","Big Ben"],["Statue of Liberty","Christ the Redeemer"],
    ["Great Wall of China","Taj Mahal"],["Pyramids of Giza","Great Sphinx"],["Colosseum","Parthenon"],["Leaning Tower of Pisa","Tower of London"],
    ["Mount Rushmore","Hollywood Sign"],["Golden Gate Bridge","Brooklyn Bridge"],["Sydney Opera House","Burj Khalifa"],["Stonehenge","Easter Island"],
    ["Machu Picchu","Chichen Itza"],["Sagrada Familia","Notre-Dame"],["Alps","Himalayas"],["Mount Everest","K2"],
    ["Sahara Desert","Gobi Desert"],["Amazon Rainforest","Congo Rainforest"],["Niagara Falls","Victoria Falls"],["Grand Canyon","Great Barrier Reef"],
    ["Pacific Ocean","Atlantic Ocean"],["Mount Fuji","Mount Kilimanjaro"],
  ],
};

// Canonical, filterable form: [{ cat, a, b }]
export const ALL_PAIRS = Object.entries(DICT).flatMap(([cat, arr]) =>
  arr.map(([a, b]) => ({ cat, a, b }))
);

export const CATEGORIES = Object.keys(DICT);
export const TOTAL_WORDS = ALL_PAIRS.length * 2;

// Sentinel used by the UI for "no specific category — pick from everything".
export const ALL_CATEGORIES = "__all__";

// Pairs to draw from for a given category selection.
export const pairsForCategory = (cat) =>
  !cat || cat === ALL_CATEGORIES ? ALL_PAIRS : ALL_PAIRS.filter((p) => p.cat === cat);
